services:
  loki:
    image: grafana/loki:3.2.0
    container_name: tracium-loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    networks:
      - tracium

  grafana:
    image: grafana/grafana:11.4.0
    container_name: tracium-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - loki
    networks:
      - tracium

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracium-api
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LOG_DIR=/app/logs
    volumes:
      - ./services/logs:/app/logs
    networks:
      - tracium

  promtail:
    image: grafana/promtail:3.2.0
    container_name: tracium-promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./services/logs:/var/log/services:ro
    depends_on:
      - loki
    networks:
      - tracium

volumes:
  loki-data:
  grafana-data:

networks:
  tracium:
    driver: bridge